apiVersion: v1
kind: Service
metadata:
  name: agentmanager-service
  namespace: arha-system 
spec:
  selector:
    app: agentmanager
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30007  # 用 NodePort 暴露，將8888綁定到30007
    - name: websocket
      port: 50051
      targetPort: 50051
      nodePort: 30008  # 用 NodePort 暴露，將50051綁定到30008
  type: NodePort
