apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arha-system-information
  namespace: arha-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem