apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arha-logs-pvc
  namespace: arha-system
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi