apiVersion: v1
kind: PersistentVolume
metadata:
  name: arha-system-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /arha/data # 儲存在 node 上的位址