apiVersion: v1
kind: PersistentVolume
metadata:
  name: arha-logs-pv
spec:
  volumeMode: Filesystem
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /arha/logs