apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  namespace: arha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: kd123456525/monitor:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: information
              mountPath: /app/information
            - name: logs-volume
              mountPath: /app/logdir
      volumes:
        - name: information
          persistentVolumeClaim:
            claimName: arha-system-information
        - name: logs-volume
          persistentVolumeClaim:
            claimName: arha-logs-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: arha-node-type
                operator: In
                values:
                - controller-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"