apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  namespace: arha-system
spec:
  type: NodePort
  selector:
    app: monitor
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30005
