apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: arha-system 
spec:
  type: NodePort
  selector:
    app: controller
  externalTrafficPolicy: Local
  ports:
    - name: controller
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30004
    - name: result
      protocol: TCP
      port: 81
      targetPort: 5001
      nodePort: 30006
